version: '3.7'

services:
  database:
    image: postgres:10.5
    container_name: database
    restart: unless-stopped
    env_file:
      - conf.env
    volumes:
      - ./.data/postgres/:/var/lib/postgresql/data/
    networks:
      - database
    expose:
      - 5432
  database-dev:
    image: postgres:10.5
    container_name: database-dev
    restart: unless-stopped
    env_file:
      - conf-dev.env
    volumes:
      - ./.data/postgres-dev/:/var/lib/postgresql/data/
    networks:
      - database-dev
    ports:
      - 6908:5432
    expose:
      - 5432
  database-radio:
    image: postgres:10.5
    container_name: database-radio
    restart: unless-stopped
    env_file:
      - conf-radio.env
    volumes:
      - ./.data/postgres-radio/:/var/lib/postgresql/data/
    networks:
      - database-radio
    ports:
      - 6900:5432
    expose:
      - 5432
  database-test:
    image: postgres:10.5
    container_name: database-test
    restart: unless-stopped
    env_file:
      - conf-test.env
    volumes:
      - ./.data/postgres-test/:/var/lib/postgresql/data/
    networks:
      - database-test
    ports:
      - 2550:5432
    expose:
      - 5432
  pgadmin:
    image: dpage/pgadmin4:4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - conf.env
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    networks:
      - database
      - database-radio
      - database-dev
      - database-test
      - pgadmin
      - traefik
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.$PRIMARY_DOMAIN`)
      traefik.http.routers.pgadmin.entrypoints: https
      traefik.http.services.pgadmin.loadbalancer.server.port: 80

networks:
  database:
    name: database
  database-radio:
    name: database-radio
  database-dev:
    name: database-dev
  database-test:
    name: database-test
  pgadmin:
    name: pgadmin
  traefik:
    external: true
