version: '3.7'

services:
  database:
    image: postgres:10.5
    container_name: database
    restart: unless-stopped
    env_file:
      - conf.env
    volumes:
      - ./.data/postgres/:/var/lib/postgresql/data/
    networks:
      - database
    expose:
      - 5432
  database-radio:
    image: postgres:10.5
    container_name: database-radio
    restart: unless-stopped
    env_file:
      - conf-dev.env
    volumes:
      - ./.data/postgres-radio/:/var/lib/postgresql/data/
    networks:
      - database-radio
    ports:
      - 6900:5432
    expose:
      - 5432
  pgadmin:
    image: dpage/pgadmin4:4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - conf.env
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    networks:
      - database
      - database-radio
      - pgadmin
      - traefik
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.$PRIMARY_DOMAIN`)
      traefik.http.routers.pgadmin.entrypoints: https
      traefik.http.services.pgadmin.loadbalancer.server.port: 80

networks:
  database:
    name: database
  database-radio:
    name: database-radio
  pgadmin:
    name: pgadmin
  traefik:
    external: true
