version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - mongo
    env_file:
      - conf.env
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongo/:/data/db

networks:
  mongo:
    name: mongo
